import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider } from "@/components/tasnstack-provider";
import StoreProvider from "@/redux/StoreProvider";
import { Host_Grotesk, Onest } from "next/font/google";

const host_grotesk = Host_Grotesk({
  subsets: ['latin'],
  // Load multiple weights for the display font
  weight: ['300','400', '500','600', '700','800'], 
  variable: '--display-family',
});

const onest = Onest({
  subsets: ['latin'],
  // Load multiple weights for the body text
  weight: ['100','200','300','400', '500', '600','700','800',"900"], 
  variable: '--text-family',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${host_grotesk.variable} ${onest.variable}`}>
        <TanstackProvider>
          <StoreProvider>{children}</StoreProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
